// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using survey_imprecise_api.Data;

namespace survey_imprecise_api.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20200429173236_AddScoreColumn")]
    partial class AddScoreColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("survey_imprecise_api.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ResponseId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("CaseId");

                    b.HasIndex("ResponseId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.CaseParameter", b =>
                {
                    b.Property<int>("CaseParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionOne")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionTwo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("CaseParameterId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SupplierId");

                    b.ToTable("CaseParameters");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.QuestionCases", b =>
                {
                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "CaseId");

                    b.HasIndex("CaseId");

                    b.ToTable("QuestionCases");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.Respondant", b =>
                {
                    b.Property<int>("RespondantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Occupation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("RespondantId");

                    b.ToTable("Respondants");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.Response", b =>
                {
                    b.Property<int>("ResponseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ChosenCaseCaseId")
                        .HasColumnType("int");

                    b.Property<int?>("RespondantId")
                        .HasColumnType("int");

                    b.HasKey("ResponseId");

                    b.HasIndex("ChosenCaseCaseId");

                    b.HasIndex("RespondantId");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Biodiversity")
                        .HasColumnType("int");

                    b.Property<int?>("Economy")
                        .HasColumnType("int");

                    b.Property<int?>("Energy")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Husbandry")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Lifequality")
                        .HasColumnType("int");

                    b.Property<int?>("Management")
                        .HasColumnType("int");

                    b.Property<int?>("Nutrients")
                        .HasColumnType("int");

                    b.Property<int?>("Soil")
                        .HasColumnType("int");

                    b.Property<int?>("Water")
                        .HasColumnType("int");

                    b.Property<int?>("Workconditions")
                        .HasColumnType("int");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.Case", b =>
                {
                    b.HasOne("survey_imprecise_api.Models.Response", null)
                        .WithMany("Choices")
                        .HasForeignKey("ResponseId");

                    b.HasOne("survey_imprecise_api.Models.Supplier", "Supplier")
                        .WithMany("Cases")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.CaseParameter", b =>
                {
                    b.HasOne("survey_imprecise_api.Models.Case", null)
                        .WithMany("Parameters")
                        .HasForeignKey("CaseId");

                    b.HasOne("survey_imprecise_api.Models.Supplier", "Supplier")
                        .WithMany("Parameters")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("survey_imprecise_api.Models.QuestionCases", b =>
                {
                    b.HasOne("survey_imprecise_api.Models.Case", "Case")
                        .WithMany("Questions")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("survey_imprecise_api.Models.Question", "Question")
                        .WithMany("Cases")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("survey_imprecise_api.Models.Response", b =>
                {
                    b.HasOne("survey_imprecise_api.Models.Case", "ChosenCase")
                        .WithMany()
                        .HasForeignKey("ChosenCaseCaseId");

                    b.HasOne("survey_imprecise_api.Models.Respondant", "Respondant")
                        .WithMany("Responses")
                        .HasForeignKey("RespondantId");
                });
#pragma warning restore 612, 618
        }
    }
}
